before_install:
- sudo apt-get update
- sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
script:
- cd tex
- mkdir _build
- pdflatex -output-directory _build ./NLP-cheatsheet.tex
deploy:
  provider: releases
  api_key:
    secure: gpJEBTenaRubyiBxjfsYVzf2eDHiJ8mSPyZjKt3+zozVcoTFWXrspESHHx6iwskNnAqZSjOG+IjWMCA77cYTYAARd3zoCeloX4pEZOGXyWhfNRGo9R+olpV9T0WitwRgtPqLusbL3s7rruDLeawnr5hUfYfBMdljrQf1LbGqzPbE1sbQE0VDpw9BEHvf5eBCp9e3R5xOEOofmMAQKLeO2hEQAsJ5+LWX3ZZEic7XDb28U5ium+xMg5L93UjUmKbb9zazJdleazMEegStlkSnLN0zamgUBGRnjcw4zUsVkv5FzkAC8nfc6+6rqPTAUIryquL6SdUc6lE0QFyiNDqmWGXLDMEuEkeff8fHIQnfcI1GVRk+hlK3+Ed+wQf88YlCS391qqsR5eHprahyaAbF2jdmZpCyk8LAj3K/9wxnK/YrVGjq7OpBnUO3RHUsfC9Veovch0H093Z8U/EWMiQbZ+2NfKZ/KerKCUY5XBXYYY1DI2bMWLf2998pORKsGE7loZnAkz7ShwVYk5prYmSA2UR6ExI3ayTckwuoi0GdRCOTA1MFb3mIoc1CUKmNWoreKt8ny/EBTK4oOi/bdy4tANwmQXx8NFpnrawqsuhCdHRdXSaf7yTIGuG46WEGC7P/4WAf1ik7LdEqYKYarqwgZ4bKklBjFSROSXNuOqpTY/I=
  file:
    - ./_build/NLP-cheatsheet.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: master
